### ISSUE TITLE
Menu Option for Toggling Between Household & Participant Modes

### ISSUE THREAD

**Issue by jasonrogena** [onaio/steps-app#106]
Add an option in the menu to switch between Household and Participant sides of the app. Do a check to make sure setting fields are filled in first; if not, show error message with link to open app settings, but opening app settings should still be password-protected. The exact wording of the option in the STEPS app will be provided by the STEPS WHO team.

Additional tasks:
- [x] User should not be able to exit settings without having filled settings for participants and households
- [x] Fix bug where switching between household and participant loses the previous page settings

**Comment by ekigamba** [comment]
Waiting for wording from the STEPS WHO team to complete the issue

**Comment by ekigamba** [comment]
Consensus between Ona + STEPS WHO team is to never let the user out of the settings screen without entering all the settings.
This eliminates the need for checking settings when switching between the household and participant modes.
