### ISSUE TITLE
Second round of QA for the android app 

### ISSUE THREAD

**Issue by akahure** [onaio/steps-app#136]
Fixes required for the App 

1. Change the name of the labels for export and import URLs on the Android app settings page. The names should be inverse i.e. Export and Import 
2. On the User ID submitting data, the user ID should appear on the web app page for submitted records as an extra measure of security 
3. Discussion point: Include a password for the user's IDs who are submitting/ synching data. Should this ID be the same ODK password or the device password set when setting up for the first time?
4. Change Survey ID to Username on the settings page of the app 
5. On the dashboard summary page, we should also synch or send the red households/ the surveys not done. This should appear on the web app 
6. Users should only be able to delete 'Not reachable' households

Web App
- Link Username to the survey ID

**Comment by akahure** [comment]
updates from discussions with Owais, Eric M and the client 

1. Change the name of the labels for export and import URLs on the Android app settings page. The names should be inverse i.e. Export and Import - confirmed that this is the change to be made
2. On the User ID submitting data, the user ID should appear on the web app page for submitted records as an extra measure of security -this is currently implemented with the new datasets that are submitted, not with the old ones
3. Discussion point: Include a password for the user's IDs who are submitting/ syncing data. Should this ID be the same ODK password or the device password set when setting up for the first time? @owais-vd discussed with the client that instead of having the admin password entered for a user to enter data, we should have a field on the settings page that will capture the password 'harshed' out. this will be the same password used in the ODK configuration setup. It should only be entered once and not every time records are required to be sent to the server 
4. Change Survey ID to Username on the settings page of the app - this comment can be ignored 
5. On the dashboard summary page, we should also synch or send the red households/ the surveys not done. This should appear on the web app. Agreed that this is pending a PR reviw. AK to get it reviewed
6. Users should only be able to delete 'Not reachable' households - this issue has changed to, the households that are flagged as 'not reachable' should appear at the bottom of the dashboards page and not at the top as is the current case.

**Comment by akahure** [comment]
Additional notes on workflow for the additional password to be included:  
3. for the ODK username and password to be included in the settings page of the android app, a chat with Owais confirms that we can have this verification included. And once a user, clicks to submit household data, the check the app will make is to ensure that 
> 1. The survey ID, Username, and Password all match what is currently in Ona 
> 2. Once confirmed on the three checks submit the data 
> 3. Should there be any mismatch - return an error message ask the user to confirm the settings or ensure that they have a connection 
 
@owais-vd @ciremusyoka

**Comment by owais-vd** [comment]
@akahure needs your input about the cloud icon which is currently showing on those households that they have submitted their survey. although, when we sent the data to the ONA server then we compile all the households into a CSV file whether the household status is done or not done or whatever. so i just want to confirm that we need to show the cloud icon all of the households that have been submitted or we will stick to the current implementation

**Comment by akahure** [comment]
@owais-vd we should confirm that all households with a cloud icon, whether complete or not have been sent to the server.

**Comment by owais-vd** [comment]
@akahure I've checked the dashboard page the category of `not reachable` is already showing at the bottom of the page just before the `total household` so i don't think to make any change for **point 6**

**Comment by owais-vd** [comment]
![Screenshot_20220125-120549_STEPS.jpg](https://user-images.githubusercontent.com/62104757/150927914-4b3960b9-383e-4bd0-aaf9-ca08e3e34475.jpg)
