### ISSUE TITLE
Canceling the selection of a participant for a size 1 household makes the household Not reachable

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#157]
Cancelling the selection of a participant for a household of size 1 adds the household to the Not reachable category. Should this be the correct workflow?

Steps to replicate:
1. Create a household
2. Add one household member
3. Move to select a participant
4. After the participant is selected, cancel the selection
The household data submitted for this household shows the status as `CANCEL_SELECTION` and not `NOT_REACHABLE` as shown below
<img width="1157" alt="Screenshot 2022-03-28 at 18 21 48" src="https://user-images.githubusercontent.com/44674982/160431872-42d13449-bb65-407e-b986-8fa29633673c.png">

For households of size >1, cancelling the selection reverts to the original household members list for participant selection to happen again.

**Comment by owais-vd** [comment]
![image](https://user-images.githubusercontent.com/62104757/161707861-ee5c9654-b00c-40e8-8a23-b748f6f0a65a.png)
we have another option to mark as `NOT REACHABLE` above the `CANCEL SELECTION`

**Comment by bkimondiu** [comment]
@owais-vd Yes. That is correct. I was raising this as a bug that when you have a household of size one (1), and you select the participant and later on cancel the selection, the status of the household is set to `NOT REACHABLE` on the app yet when you submit the household data, the status on the web app is set to `CANCEL_SELECTION`. Please follow the steps [here](https://github.com/onaio/steps-app/issues/157#issue-1183607125) to replicate the bug.

**Comment by owais-vd** [comment]
if we cancel the selection that means we can re-select the member again but if we set the household status `NOT REACHABLE` on cancelation that means we cannot be done the selection again. However, in the Total summary screen, we are merging the cancelation count in the  `NOT REACHABLE` category. Please check the second option of this comment https://github.com/onaio/WHOSteps/issues/16#issuecomment-913503870

**Comment by bkimondiu** [comment]
This issue is no longer valid. Tested it again with @owais-vd and it works as expected.
