### ISSUE TITLE
Investigate the Bootstrap Activity

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#195]
The auditor shared the following:
```
(androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity) is not Protected. 
[android:exported=true]

(androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity) is not Protected. 
[android:exported=true]

(androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity) is not Protected. 
[android:exported=true]

```
With the description that 
`An Activity is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device.`

**Comment by owais-vd** [comment]
All three activities have no security implications as they are all launchable instrumentation test activities and intentionally exported `true` by the library. `A launchable activity must be exported as of Android 12`.

cc: @bkimondiu @ukanga @ekigamba

**Comment by ekigamba** [comment]
@owais-vd Are these activities disabled in the release version? If not, can we disable them since we do not currently use instrumentation testing.
