### ISSUE TITLE
Disable logging to external storage

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#198]
[App can read/write to External Storage. Any App can read data written to External Storage.](https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#external-storage)

Standards:
```
CWE: CWE-276: Incorrect Default Permissions 
OWASP Top 10: M2: Insecure Data Storage 
OWASP MASVS: MSTG-STORAGE-2
```

Files:
`com/onaio/steps/activities/BackupLocati onActivity.java com/onaio/steps/handler/actions/SaveT oSDCardHandler.java com/onaio/steps/helper/Logger.java `

**Comment by ekigamba** [comment]
The removed version is here for future references https://github.com/onaio/steps-app/blob/499c35717b839dbcfeb0e679b196d0a25fc917e6/src/main/java/com/onaio/steps/helper/Logger.java
