### ISSUE TITLE
Rebuild the APK and sign with v2 and/or v3

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#201]
This will help resolve the following:

1. Application vulnerable to Janus Vulnerability - `Application is signed with v1 signature scheme, making it vulnerable to Janus vulnerability on Android 5.0-8.0, if signed only with v1 signature scheme. Applications running on Android 5.0-7.0 signed with v1, and v2/v3 scheme might also be vulnerable.`
2. Certificate algorithm might be vulnerable to hash collision - `Application is signed with SHA1withRSA. SHA1 hash algorithm is known to have collision issues. The manifest file indicates SHA256withRSA is in use.`

**Comment by owais-vd** [comment]
we are using `minSdkVersion 21 lollipop` and I think we can switch the signature scheme while building a release APK. However, this link https://jokester.github.io/posts/2017-02-28/sha1-collision-and-apk-signing/ can help to get more context. cc: @bkimondiu

**Comment by ndegwamartin** [comment]
We'll need to sign with V1 as well for versions below Android 7 . See [SO post here](https://stackoverflow.com/questions/46967840/getting-error-jar-sig-no-manifest-missing-meta-inf-manifest-mf-when-pushing-an) and [Android documentation here](https://source.android.com/security/apksigning) for maximum compatibility
