### ISSUE TITLE
Disable app functionality on a rooted device

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#215]
**Observation**
We were able to install and use the mobile application using a rooted android phone

**Impact**
Rooted devices and Jail broken devices can be used to access sensitive application files. This type of access can be utilised by an attacker to compromise the security of the application

**Recommendations**
The application should be configured to check for rooted and jail broken devices. Upon initiation on a rooted or jail broken device, the application should not initialise.

**Comment by owais-vd** [comment]
@bkimondiu Could we show the alert dialog when a rooted device is detected like `Alert: it looks like your device is rooted.` and exit the app.

**Comment by ekigamba** [comment]
@owais-vd @bkimondiu 

- [ ] Detect root at boot and delete all data if rooted
- [ ] Detect root when the application opens and delete all data
- [ ] Prevent app operation when the app is openned on a rooted device
- [ ] Show a cancelleable screen with the message. `STEPS app does not operate on rooted or jail-broken devices. Any previous data has been deleted for security reasons. Kindly install on an appropriate device or contact your system administrator`. The app should close once the screen is cancelled/OK-ayed
