### ISSUE TITLE
Error text instead of dialog when submitting household data

### ISSUE THREAD

**Issue by bkimondiu** [onaio/steps-app#219]
The user `rnawaz` was not assigned a form on the STEPS web app but they had access to Ona Data and could download the forms into ODK Collect. They encountered the error below when submitting household data - this is instead of this [dialog](https://github.com/onaio/steps-app/issues/171#issuecomment-1099940815).
[Error on STEPS apk.pdf](https://github.com/onaio/steps-app/files/9189424/Error.on.STEPS.apk.pdf)

You can also get error on this file https://drive.google.com/file/d/1fJEm_GZvLmR51HFcjdhSWwyhQOa0zeY3/view?usp=sharing

**Comment by owais-vd** [comment]
could you please share a steps video? THanks

**Comment by bkimondiu** [comment]
@owais-vd The user shared a screenshot of the dialog below but it must not have rendered correctly on email since all I got was the text I shared with you. The issue was resolved when I shared permission to submit data to the form. This issue is therefore irrelevant.

![dialog - error](https://user-images.githubusercontent.com/44674982/182131034-1ceea35d-6e2e-4514-840a-5c7bd7a73e11.png)
