### ISSUE TITLE
Error when trying to edit unfinalized forms

### ISSUE THREAD

**Issue by samwata** [onaio/steps-app#221]
We have a case where a user is trying to continue with unfinalized forms but they get error "please try later"
The issue seems to affect one user so far and we have not been able to replicate it.
Can we get the logs on when the issue happened?

Steps to reproduce
Download a form from Steps projects on ODK Collect
register a household and select a member to interview
collect data and stop at some point
come back and try to continue with data collection from Steps app

I have attached a video client sent 

https://github.com/onaio/steps-app/assets/23456184/b674f8e2-94f8-4814-8adc-45f0ae7f5854

**Comment by bkimondiu** [comment]
The issue has been created in a different repo https://github.com/opensrp/support/issues/321
