### ISSUE TITLE
Locale Message for Invalid Participant Error Message

### ISSUE THREAD

**Issue by jasonrogena** [onaio/steps-app#43]
We'll need the following message translated to all the supported languanges (Arabic, Spanish, French, Russian):
```
Invalid Participant, please fill or correct the following fields:
```

Related to issue #39

**Comment by cagulas** [comment]
Have added this string to the translation spreadsheet: https://docs.google.com/spreadsheets/d/1UL04IvdQz2gZ113vLOH_9fSmPVZTlIZRn3Mwy_v2y_Q/edit#gid=2025337757
