### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by jasonrogena** [onaio/steps-app#48]
Update the welcome message in all the supported languages from:

```
Welcome! Start using the WHO STEPS app by entering your Device ID in the app settings.
```

to something like:

```
Welcome! Start using the WHO STEPS app by selecting the app type.
```

Mainly because fixing issue #34 means that users will no longer be able to manually enter the device ID.

**Comment by cagulas** [comment]
Yes, that's correct. Let's leave the welcome message as is until and unless we hear otherwise from WHO.
