### ISSUE TITLE
Add screenshot and description to the readme

### ISSUE THREAD

**Issue by mberg** [onaio/steps-app#58]
@jasonrogena can you add a screenshot or two on the readme / index page for this project.

@cagulas  can you do a short couple sentence description of what this app does?

**Comment by cagulas** [comment]
How about this?

`STEPS is an Android application developed for the World Health Organization's STEPwise approach to noncommunicable disease risk factor surveillance. The app is used to register households and household members during survey rounds and then randomly select a household member to interview. Once a household member is selected for interview, the survey is launched in the ODK Collect app.`

`For more information, see http://www.who.int/chp/steps/en/.`

**Comment by jasonrogena** [comment]
Here are three screenshots that might work well with @cagulas' description:
![screenshot_20161019-095654](https://cloud.githubusercontent.com/assets/2384176/19508932/a3d13fca-95e4-11e6-8488-0b91ed2737f3.png)
![screenshot_20161019-094758](https://cloud.githubusercontent.com/assets/2384176/19508953/ae5b1ec0-95e4-11e6-978c-9d8b8903a537.png)
![screenshot_20161019-094827](https://cloud.githubusercontent.com/assets/2384176/19508957/b74d5e26-95e4-11e6-8ad1-9a41e001e96b.png)

**Comment by cagulas** [comment]
@jasonrogena these look great. I think you can update the readme page with these now.

**Comment by jasonrogena** [comment]
@cagulas It might be a good idea listing the supported languages, no?

**Comment by cagulas** [comment]
This is done, closing. Will create new issue if there are any changes requested from the client.
